lista = {
    "categorias": {
        1: "pintura",
        2: "escultura",
        3: "fotografia",
    },
    "autores": {
        1: {
            "nome": "Alexandre Cabanel",
            "foto": "Alexandre_Cabanel.jpg",
            "biografia": "Alexandre Cabanel foi um pintor francês, representante do Neoclassicismo Acadêmico. Dedicou-se a assuntos históricos, mitológicos e religiosos. Foi também autor de retratos, paisagens e composições decorativas. Excelente aquarelista.",
            "obras": [1,2],
        },
        2: {
            "nome": "Michelangelo",
            "foto": "Michelangelo.jpg",
            "biografia": "Michelangelo di Lodovico Buonarroti Simoni, mais conhecido simplesmente como Michelangelo ou Miguel Ângelo, foi um pintor, escultor, poeta, anatomista e arquiteto italiano, considerado um dos maiores criadores da história da arte do ocidente.",
            "obras": [3,4],
        },
        3: {
            "nome": "Henri Cartier",
            "foto": "Henri_Cartier-Bresson.jpg",
            "biografia": '''Henri Cartier-Bresson foi um fotógrafo, fotojornalista e desenhista francês que fundou a agência fotográfica Magnum junto com Bill Vandivert, Robert Capa, George Rodger e David Seymour "Chim". Tornou-se também o primeiro fotógrafo da Europa Ocidental a registrar a vida na União Soviética de maneira livre. Fotografou os últimos dias de Gandhi e os eunucos imperiais chineses, logo após a Revolução Cultural. ''',
            "obras": [5,6],
        },
    },
    "obras": {
        1:{
            "nome": "O anjo caido",
            "img": "o_anjo_caido.jpg",
            "descricao": "O Anjo Caído – em francês, L'Ange déchu – é uma pintura do artista francês Alexandre Cabanel. Foi pintada em 1847, quando o artista tinha 24 anos, e representa Lúcifer após sua queda do paraíso.",
            "categoria": 1,
            "autor": 1,
            "data_texto": "1847",
            "leilao": False,
            "exibicao": True,
            "id_exibicao": 1,
            "comentarios": [1,2],
        },
        2:{
            "nome": "Napoleão III",
            "img": "napoleaoIII.jpg",
            "descricao": "O retrato de estado em tamanho real foi concluído por Alexandre Cabanel a pedido do próprio imperador.",
            "categoria": 1,
            "autor": 1,
            "data_texto": "1865",
            "leilao": True,
            "exibicao": False,
            "id_exibicao": 0,
            "comentarios": [3,4],
        },
        3:{
            "nome": "David",
            "img": "David.jpg",
            "descricao": "David ou Davi é uma das esculturas mais famosas do artista renascentista Michelangelo. O trabalho retrata o herói bíblico com realismo anatômico impressionante, sendo considerada uma das mais importantes obras do Renascimento.",
            "categoria": 2,
            "autor": 2,
            "data_texto": "1501",
            "leilao": False,
            "exibicao": True,
            "id_exibicao": 1,
            "comentarios": [5,6],
        },
        4:{
            "nome": "Centauromaquia",
            "img": "Centauromaquia.jpg",
            "descricao": "Neste relevo, Michelangelo se refere a um sarcófago romano, daí o formato de púlpito de Giovanni Pisano, e o relevo contemporâneo de bronze de Bertoldo di Giovanni com uma batalha de cavaleiros, estando preso em um sarcófago do Camposanto de Pisa, apesar de que no relevo de Michelangelo, vemos exaltado a dinâmica dos corpos nus e anulada cada referência espacial.",
            "categoria": 2,
            "autor": 2,
            "data_texto": "1492",
            "leilao": False,
            "exibicao": True,
            "id_exibicao": 2,
            "comentarios": [7,8],
        },
        5:{
            "nome": "Man Jumping The Puddle",
            "img": "man_jumping_the_puddle.webp",
            "descricao": "Esta fotografia é ‘Man Jumping the Puddle‘ também conhecida como ‘Behind the Gare Saint-Lazare‘. É uma das fotos mais influentes e discutidas do mundo. Assim como a fotografia, o fotógrafo por trás dela também é significativo na história da fotografia.",
            "categoria": 3,
            "autor": 3,
            "data_texto": "1930",
            "leilao": True,
            "exibicao": False,
            "id_exibicao": 0,
            "comentarios": [9,10],
        },
        6:{
            "nome": "Madrid, Spain",
            "img": "madrid-spain-1933.jpg",
            "descricao": "Em 1933, apenas três anos antes do início da Guerra Civil Espanhola, Henri Cartier-Bresson viajou para a Espanha com sua recém-adquirida câmera Leica e produziu imagens que provaram ser registros poderosos e duradouros da época.",
            "categoria": 3,
            "autor": 3,
            "data_texto": "1933",
            "leilao": False,
            "exibicao": True,
            "id_exibicao": 2,
            "comentarios": [11,12],
        },
        
    },
    "comentarios": {
        1: {
            "usuario": "@ArtLover93",
            "data": "1/1/2024",
            "mensagem": "Essa pintura é simplesmente hipnotizante! As cores parecem dançar juntas. 😍",
            "lance": False,
            "lance_valor": 0.00,
        },
        2: {
            "usuario": "@BeatrizPincelada",
            "data": "1/1/2024",
            "mensagem": "As texturas aqui são impressionantes! Parece que posso tocar e sentir a história por trás.",
            "lance": False,
            "lance_valor": 0.00,
        },
        3: {
            "usuario": "@ArteiraAna",
            "data": "1/1/2024",
            "mensagem": "Dou meu lance: $5.000 pela pintura! Essa obra precisa estar na minha coleção. 🎨✨",
            "lance": True,
            "lance_valor": 5000.00,
        },
        4: {
            "usuario": "@ColecionadorCarlos",
            "data": "1/1/2024",
            "mensagem": "Lance de $6.500! Essa peça é um clássico e vale cada centavo!",
            "lance": True,
            "lance_valor":6500.00,
        },
        5: {
            "usuario": "@EscultorEmAção",
            "data": "1/1/2024",
            "mensagem": "A precisão dos detalhes é surreal! Parece que a escultura vai ganhar vida a qualquer momento.",
            "lance": False,
            "lance_valor": 0.00,
        },
        6: {
            "usuario": "@OlhosParaArte",
            "data": "1/1/2024",
            "mensagem": "Essa escultura transmite tanta força e delicadeza ao mesmo tempo. Simplesmente impressionante.",
            "lance": False,
            "lance_valor": 0.00,
        },
        7: {
            "usuario": "@3DNatural",
            "data": "1/1/2024",
            "mensagem": "Nunca pensei que pedra pudesse parecer tão suave. Um equilíbrio perfeito entre arte e natureza.",
            "lance": False,
            "lance_valor": 0.00,
        },
        8: {
            "usuario": "@MarianaDasMãos",
            "data": "1/1/2024",
            "mensagem": "A pose dessa escultura é tão expressiva! É como se cada movimento contasse uma história.",
            "lance": False,
            "lance_valor": 0.00,
        },
        9: {
            "usuario": "@FotoFanático",
            "data": "1/1/2024",
            "mensagem": "Lance de $3.000! Essa fotografia merece um lugar de destaque na minha galeria. 📸",
            "lance": True,
            "lance_valor": 3000.00,
        },
        10: {
            "usuario": "@PaisagemPura",
            "data": "1/1/2024",
            "mensagem": "Vou de $3.800! A luz e a composição dessa imagem são simplesmente únicas.",
            "lance": True,
            "lance_valor": 3800.00,
        },
        11: {
            "usuario": "@ClicandoMundos",
            "data": "1/1/2024",
            "mensagem": "Essa foto captura um momento tão genuíno. Dá pra sentir a emoção através da imagem!",
            "lance": False,
            "lance_valor": 0.00,
        },
        12: {
            "usuario": "@DetetiveDosDetalhes",
            "data": "1/1/2024",
            "mensagem": "Olhem os pequenos detalhes ao fundo! É isso que faz essa fotografia tão especial.",
            "lance": False,
            "lance_valor": 0.00,
        },
    },
    "exibicoes": {
        1: {
            "nome": "Ressonâncias da Luz",
            "local": "Museu de Arte Moderna de Paris (Musée d'Art Moderne de Paris), Paris, França",
            "data": "5 de abril de 2025 a 20 de junho de 2025",
            "curador": "Sophie Morel",
            "obras": [1,3]
        },
        2:{
            "nome": "Fragmentos Eternos",
            "local": "Palazzo Pitti, Florença, Itália",
            "data": "1º de setembro de 2025 a 30 de novembro de 2025",
            "curador": "Alessio Fontana",
            "obras": [4,6]
        }
    },
}